travis:
  secure:
    BINSTAR_TOKEN: kepne+FkxFsbHQmkNp7hRCxqQIRyK3bXRs7FrOMUBiY9QTXO7UB5cBC+m0dk6EoCpwWTY8HUzVl1rWpY+F4C8hItQkwtOidJjcpW/roTF/YSBhYxk6+qsiSdTr/1T8LtobioWkYMWInDsRHREpUnRWNehBDG1vK0RV7IL9fx7AseSuHyTTXqsYlgQNnjHnT1N9pcPZy0CeHZMaXXvBxB2qREgGNGjG/Re6zOL2vek7VldF1VBeY6DOSJFRXFXIZlLVOdluBVb1QULhT1b5KBy7Epjqsm743m+QMStk3cwJbbeMubridtOwasqS+M1EPQtQ/JdPWMuoqxO+gj1XmZ+hB5uv3kRWI420r4KrOrsbpKlvfumeTB/Bkma7izC3cNM0da7og97aCsc+ODOYLc07fuABMgv8idwWf89TV4PRC2XTimTihqgxXDIh7fHevMLBx4inqCjnzyE6DNVVUFZml69mLPSHBiKgZtD6uYYXRzjtv89gAyEi1Y7BTgCoQqhKlVpyMIJX5ETw0Z9VyEWEjKPrw+Q+NW+caARGUM2B+kxFT679L3JkA1FLa4NK3fUWE9VXHLHQm5g6JrkJgrrTWchi0VLp46eSg+xCKGaTLiohhhzAXp9yAWXxO8iA+8+/RP3tN28rDl5AS8msBNUc1OdtQOZPI6eMK9VysShBI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
