travis:
  secure:
    BINSTAR_TOKEN: LrVXipeL249IHNiaMaNrRtNris2V/lP9PcZcfoJpJNXbMVeaX9ADWl2dzQhDDubwnNXhWPneywOc+kLAgkZHI2Rg5X9gCeaClpcN19oa0kXNX/bZh2fZo1cYcc3xoQYwpJQHzEZaKdYCQH0ZExNzTof7jZ9jjOaUj7UCDxIKZRE+DoV8/zox9AvGyz456aWIAysFH6omMBXIUYj66SxMUcilryIS+NVJW3jwn4fm3Cy8qxKaanOLv6FCmbX0gDQ3wwHYDwt4RrK5UFbX/SMx30Gvv3J/8XZU8S7PHcZNP+ynuCaIFVnch3lv8tp2RF+5xDL1hHRL1bCjNay3oxmS5967411lL0x8CeVgepxalf52cd7zGD8T3v9ex857iJCzMwR0DAnZQeJHPjzEo9E9Gpppz1KvNKcxt/joMICzXxyPHZodZm4T3JhZKDP1A17SVCXYNlXqX+g3B9vtjC/vJoiHW7bolozAto09K8tWjjag86EkIuimV1Y1xfch7O8qsFlTFhRrBnQFSBbNtGOVKhkWb6ILh8+y3/xXt7aJPuIdv17k+uLshcLvlSBdSbhTEWZeJjSRVlBjxdD2l9KOjLzoVxK0MQbW6Gzd3C2JhfgRBF15XoTsejjRxBEESHsSgQfmWVbeyvS8PUkIf6N8l+ngLF8JUkVifIu19CClzPY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
