travis:
  secure:
    BINSTAR_TOKEN: lwI1zFJ3lg+W24h87VnArb0K0Tv5GVyE23WKqYyie3FB9CAtZbCMbNQ3ZUMUC9EsM9IUZZ8sxQSEHuR4dI37vWwed9AjZnuY8JZAQx/Q5Q2gvU4TSbsyscGs8UP0mxMbrWa0CcEFsMNkyRlD+KcUugVSBjA71kcrPgMC4IYU5exKYftEZQVu1RLNiNxTBxsrFNHgvVMxZRL5+9syQ0tfuCT8TIrziSTaXj9P461XCftRN8r70z+T4fexz/mzWfG5jAtq10oQuhm5yVOgjS8GGBN9/Of5UDmTI5SEA/enptodgtcpAXwkn7rL5bj/ACPCHZdeJAcnURUYYPguoz8PoZ3NRAR9hISLSgkF6RSgSmorP9jMssC7w4jtMY/dNZ3BZm4YVc1Z7h0UJ0v6mf9xUVBRJkHtDzb1E9xLtRS6E3EHPxmUVpQNaS1NnkZsr4jG+ZH3Lsl0eIKvFevV1q9SNK51tulhZKbp8mBA8TN9//TJxh3UcX5LDwypW5MvSo/n9/jQHjiZCswSTRzmwYeW7nrcIxkyW1vzkKjl4OE5+Gmv5TFtKd7CqcFZKjWUtfALCmpvPGzCYphuA/ZZ2zTWssCxyg3gi6Bn+Axj/LeO/uGXwwIcdrVShz0JtPnRsY6R1y8dEG0vXh3Mm1PqxRuUddzsO+yXx2+h3ZY0RPu4QU8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
